# profile/config.yaml
cluster: "sbatch --job-name={rule} \
                 --cpus-per-task={threads} \
                 --time=7-0:0:0 \
                 --mail-type=END,FAIL \
                 --mail-user=abemania@fredhutch.org \
                 --output=logs/{rule}_%j.out \
                 --error=logs/{rule}_%j.err"
jobscript: "profile/slurm-jobscript.sh"
jobs: 50
latency-wait: 60

default-resources:
    - threads=16
    - mem_mb=64000
    - disk_mb=16000

restart-times: 2
keep-going: true
printshellcmds: true

# Usage: snakemake --profile ./profile --cores 32 --resources duckdb_lock=1
# The duckdb_lock resource constraint ensures only one DuckDB-accessing job runs at a time